### ISSUE TITLE
Correcting navbar elements

### ISSUE THREAD

**Issue by abhivarma174** [omrajsharma/bigohhh.com#11] opened 2024-05-10 12:39 UTC
The elements in the navigation bar are not aligned properly. I can place all of the elements to the end.

**Comment by abhivarma174** [comment] 2024-05-10 12:39
Kindly assign me the issue. I want to contribute as part of GSSOC'24

**Comment by sahi123-cloud** [comment] 2024-05-10 14:52
can u please assign this task for me by labelling it under gssoc

**Comment by IP80808080** [comment] 2024-05-10 15:28
👋 Hello! I'd be happy to help with this issue. Could you please assign it to me? Additionally, could you please label it for the appropriate level? Thank you! 🚀

**Comment by Kashishoza** [comment] 2024-05-10 16:14
please assign me this task under gssoc 2024

**Comment by omrajsharma** [comment] 2024-05-10 21:08
@abhivarma174 can you please show what exactly the issue is using screenshot?

**Comment by abhivarma174** [comment] 2024-05-10 21:12
![nav-bar](https://github.com/omrajsharma/bigohhh.com/assets/111688945/ff1b10cf-a71e-4baa-8057-7588c8bbad59)

**Comment by abhivarma174** [comment] 2024-05-10 21:14
![nav-bar](https://github.com/omrajsharma/bigohhh.com/assets/111688945/90e27019-1a9c-4cfe-9326-66868c184010)

Here in the nav-bar we can see that the Home,Courses,testimonials,Mentor sections are not aligned to end of the screen.They are at the middle of the screen thus making it look inaprropriate at first glance.I can fix this issue.

**Comment by omrajsharma** [comment] 2024-05-10 21:34
@abhivarma174 this is our expectations from navbar. We are going to bring a signin and signup button on the right hand side That is why the right side space is empty.

**Comment by omrajsharma** [comment] 2024-05-12 12:18
We're closing this issue

**Closed by omrajsharma** 2024-05-12 12:18 UTC
